on:
  push:
    branches:
      - main
name: Render and Publish
permissions: 
    contents: write
    pages: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          python-version: 3.9

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3
      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install - requirements.txt

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
        #with:
        #  target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      
